### ISSUE TITLE
New term request for Technique controlled values

### ISSUE THREAD

**Issue by jocelynmora** [BICCN/TMN#71]
For new term requests, please provide the following information:

## Preferred term label

MRI

## Synonyms

Magnetic Resonance Imaging

## Textual definition

A technique that produces cross-sectional images of a patient's body, using magnetism and radio waves.

What is an MRI scan and what can it do? Drug Ther Bull. 2011 Dec;49(12):141-4. doi: 10.1136/dtb.2011.02.0073. PMID: 22170411.

## Suggested parent term

Hoping to add this term to Technique controlled values list.

## Attribution

n/a

**Comment by patrick-lloyd-ray** [comment]
Thank you, @jocelynmora.

**Comment by patrick-lloyd-ray** [comment]
Term in tmn as imported (OBI:0002985 ## magnetic resonance imaging assay)
