### ISSUE TITLE
New term request for Data Collection controlled values list

### ISSUE THREAD

**Issue by jocelynmora** [BICCN/TMN#72]
For new term requests, please provide the following information:

## Preferred term label

fischl_lsfm

## Synonyms

Light sheet fluorescence microscopy

## Textual definition

A fluorescence microscopy technique with an intermediate-to-high optical resolution and optical sectioning capabilities at high speed. 

Santi PA. Light sheet fluorescence microscopy: a review. J Histochem Cytochem. 2011 Feb;59(2):129-38. doi: 10.1369/0022155410394857. PMID: 21339178; PMCID: PMC3201139.

## Suggested parent term

Hoping to add to Data Collection controlled values list.

## Attribution

n/a

**Comment by patrick-lloyd-ray** [comment]
Thank you, @jocelynmora.

**Comment by patrick-lloyd-ray** [comment]
Term already exists: TMN:0000017 -- light sheet fluorescence microscopy assay.
