### ISSUE TITLE
Term request for Nanopore sequencing

### ISSUE THREAD

**Issue by kasbaker** [BICCN/TMN#74]
## Preferred term label

nanopore sequencing

## Synonyms

ONT

Oxford Nanopore Sequencing

## Textual definition

https://nanoporetech.com/applications/dna-nanopore-sequencing

## Suggested parent term

BAO:0003027  (RNA sequencing)

BAO:0040026  (DNA sequencing)

The technique sequences cDNA, which is dervied from RNA

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/TMN)

## Comments

Oxford Nanopore is one commercial entity that provides this assay, but other nanopore sequencing technologies exist.

**Comment by patrick-lloyd-ray** [comment]
Thanks, @kasbaker!
