### ISSUE TITLE
ERO is inactive

### ISSUE THREAD

**Issue by shawntanzk** [BICCN/TMN#80]
Currently imports are failing cause ERO is inactive: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/ero.md
It is currently grabbing an empty ERO.owl file (http://purl.obolibrary.org/obo/ero.owl) 
You can either 1) redirect this to a ERO.owl file that you have on a repo somewhere? 
Or preferentially remove ERO imports and replace terms with active ontology terms

**Comment by patrick-lloyd-ray** [comment]
Probably the latter -- I can create new terms if I cannot find suitable replacements.
